language: java
jdk:
  - openjdk8
before_script:
  - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"
script:
  - fossa init
  - fossa analyze
